### ISSUE TITLE
NameError: name 's' is not defined

### ISSUE THREAD

**Issue by Alfro** [Fredster64/Randomly-Generated-Maze#15]
**Branch:** master
After creating the maze, the program throws an Exception:
```
  File "/home/alfro/projects/Randomly-Generated-Maze/Objects.py", line 138, in centre
    return v(0.5*(self.v1[0]+self.v2[0]), 0.5*(self.v1[1]+self.v2[1]), s)
NameError: name 's' is not defined
```
The function "centre" does not have an 's' variable, and neither is present as a global.

Full output:
```
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
Welcome to the maze!
You start in the top-left corner and can move left, right, up or down.
Please choose how long and wide you want the maze to be.
What length? 10
What width? 10
Would you like to play as a cat or a dog?
dog
Loading...
Traceback (most recent call last):
  File "Maze.py", line 14, in <module>
    main()
  File "Maze.py", line 9, in main
    gameEngine = GameEngine()
  File "/home/alfro/projects/Randomly-Generated-Maze/GameEngine.py", line 44, in __init__
    dm.drawMaze(self.maze, s, self.gameDisplay, self.surface)
  File "/home/alfro/projects/Randomly-Generated-Maze/Drawing_Maze.py", line 45, in drawMaze
    rotv1 = rot(pi/2, v1, centre(edgeToAdd))
  File "/home/alfro/projects/Randomly-Generated-Maze/Objects.py", line 138, in centre
    return v(0.5*(self.v1[0]+self.v2[0]), 0.5*(self.v1[1]+self.v2[1]), s)
NameError: name 's' is not defined
```

**Comment by Alfro** [comment]
Wait, it looks like you tried to add the `centre` and `vertexEq` functions as part of the `edge` class (since they have a "self" attribute). However, those functions are currently not indented, which means they're part of the Objects.py module instead of part of "edge".

Maybe take a look at that if you're still playing with this code?

**Comment by Fredster64** [comment]
Hi, 
Thanks for noticing this. The issue *should* be relatively straightforward to sort out, so I'll get on it now.

**Comment by Fredster64** [comment]
I've fixed the 's' syntax error and the game now runs on my laptop without any bugs or error messages. @Alfro don't hesitate to let me know if you find any further issues, I really appreciate it! 
For now, though, I'm going to close this issue.

**Comment by Alfro** [comment]
It works now. Gj!
